MainWebApp/Omazon/Omazon/Controllers/AdminController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.Extensions.Configuration;
using Omazon.Models;
using System.Data;

namespace Omazon.Controllers
{
    public class AdminController : Controller
    {
        public IConfiguration Configuration { get; }

        public AdminController(IConfiguration configuration)
        {
            Configuration = configuration;
        }
        // GET: AdminController
        public ActionResult Index()
        {
            return View();
        }

        // GET: AdminController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: AdminController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: AdminController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreateProduct(ProductoModel producto)
        {
            string connectionString = Configuration["ConnectionStrings:DB_Connection"];
            var connection = new SqlConnection(connectionString);

            string sqlQuery = $"exec [PRODUCTO].[sp_INSERT_PRODUCTOS] @p_NOMBRE_PRODUCTO = '{producto.NombreProducto}'," +
                  $"@p_STOCK={producto.Stock}, @p_PRECIO={producto.Precio}," +
                  $"@p_RUTA_IMAGEN='{producto.RutaImagen}',@p_ID_CATEGORIA={producto.IDCategoria}";
            using (SqlCommand command = new SqlCommand(sqlQuery, connection))
            {
                command.CommandType = CommandType.Text;
                connection.Open();
                command.ExecuteReader();
                connection.Close();
            }

            return Redirect("~/Producto/Index");
        }

        // GET: AdminController/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: AdminController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EditProduct(ProductoModel producto)
        {
            string connectionString = Configuration["ConnectionStrings:DB_Connection"];
            var connection = new SqlConnection(connectionString);

            string sqlQuery = $"exec [PRODUCTO].[sp_UPDATE_PRODUCTOS] @p_ID_PRODUCTO={producto.IdProducto}, " +
                  $"@p_NOMBRE_PRODUCTO = '{producto.NombreProducto}'," +
                  $"@p_STOCK={producto.Stock}, @p_PRECIO={producto.Precio}," +
                  $"@p_RUTA_IMAGEN='{producto.RutaImagen}', @p_ID_CATEGORIA ={producto.IDCategoria}";
            using (SqlCommand command = new SqlCommand(sqlQuery, connection))
            {
                command.CommandType = CommandType.Text;
                connection.Open();
                command.ExecuteReader();
                connection.Close();
            }

            return Redirect("~/Producto/Index");
        }

        // GET: AdminController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: AdminController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteProduct(ProductoModel producto)
        {
            string connectionString = Configuration["ConnectionStrings:DB_Connection"];
            var connection = new SqlConnection(connectionString);
        
            string sqlQuery = $"exec [PRODUCTO].[sp_DELETE_PRODUCTOS] @p_ID_PRODUCTO={producto.IdProducto}";
            using (SqlCommand command = new SqlCommand(sqlQuery, connection))
            {
                command.CommandType = CommandType.Text;
                connection.Open();
                command.ExecuteReader();
                connection.Close();
            }

            return Redirect("~/Producto/Index");
        }
    }
}

MainWebApp/Omazon/Omazon/Controllers/ProductoController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Nest;
using Omazon.Models;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;
using System.Security.Claims;
using System.Threading.Tasks;

namespace Omazon.Controllers
{
    public class ProductoController : Controller
    {
        public IConfiguration Configuration { get; }
        private readonly ElasticClient _client;

        public ProductoController(IConfiguration configuration, ElasticClient client)
        {
            Configuration = configuration;
            _client = client;
        }

        public ActionResult Index()
        {
            string connectionString = Configuration["ConnectionStrings:DB_Connection"];
            var connection = new SqlConnection(connectionString);

            string sqlQuery = $"exec PRODUCTO.sp_SELECT_PRODUCTOS";
            using (SqlCommand command = new SqlCommand(sqlQuery, connection))
            {
                command.CommandType = CommandType.Text;
                connection.Open();
                SqlDataReader respuestaReader = command.ExecuteReader();

                List<ProductoModel> productos = new List<ProductoModel>();
                while (respuestaReader.Read())
                {
                    ProductoModel producto = new ProductoModel();
                    producto.IdProducto = Int32.Parse(respuestaReader["ID_PRODUCTO"].ToString());
                    producto.NombreProducto = respuestaReader["NOMBRE_PRODUCTO"].ToString();
                    producto.Stock = Int32.Parse(respuestaReader["STOCK"].ToString());
                    producto.Precio = int.Parse(respuestaReader["PRECIO"].ToString());
                    //producto.IdProveedor = Int32.Parse(respuestaReader["ID_PROVEEDOR"].ToString());
                    producto.NombreProveedor = respuestaReader["NOMBRE_PROVEEDOR"].ToString();
                    producto.NombreCategoria = respuestaReader["NOMBRE_CATEGORIA"].ToString();
                    producto.RutaImagen = respuestaReader["RUTA_IMAGEN"].ToString();
                    productos.Add(producto);
                }
                connection.Close();
                ViewBag.Productos = productos;
            }

            sqlQuery = $"exec [OMAZON].[sp_SELECT_CATEGORIA]";
            using (SqlCommand command = new SqlCommand(sqlQuery, connection))
            {
                command.CommandType = CommandType.Text;
                connection.Open();
                SqlDataReader respuestaReader = command.ExecuteReader();

                List<CategoriaModel> categorias = new List<CategoriaModel>();
                while (respuestaReader.Read())
                {
                    CategoriaModel categoria = new CategoriaModel();

                    categoria.IdCategoria = Int32.Parse(respuestaReader["ID_CATEGORIA"].ToString());
                    categoria.NombreCategoria = respuestaReader["NOMBRE_CATEGORIA"].ToString();

                    categorias.Add(categoria);

                }
                connection.Close();
                ViewBag.Categorias = categorias;
            }
            return View();
        }
        [HttpPost]
        public ActionResult Index(ProductoModel productoModal)
        {
            string connectionString = Configuration["ConnectionStrings:DB_Connection"];
            var connection = new SqlConnection(connectionString);

            string sqlQuery = $"exec [OMAZON].[sp_BUSCAR_PRODUCTO_NOMBRE] @NOMBRE_BUSCAR='{productoModal.NombreProducto}'";
            using (SqlCommand command = new SqlCommand(sqlQuery, connection))
            {
                command.CommandType = CommandType.Text;
                connection.Open();
                SqlDataReader respuestaReader = command.ExecuteReader();

                List<ProductoModel> productos = new List<ProductoModel>();
                while (respuestaReader.Read())
                {
                    ProductoModel producto = new ProductoModel();

                    producto.IdProducto = Int32.Parse(respuestaReader["ID_PRODUCTO"].ToString());
                    producto.NombreProducto = respuestaReader["NOMBRE_PRODUCTO"].ToString();
                    producto.Stock = Int32.Parse(respuestaReader["STOCK"].ToString());
                    producto.Precio = int.Parse(respuestaReader["PRECIO"].ToString());
                    //producto.IdProveedor = Int32.Parse(respuestaReader["ID_PROVEEDOR"].ToString());
                    producto.NombreProveedor = respuestaReader["NOMBRE_PROVEEDOR"].ToString();
                    producto.NombreCategoria = respuestaReader["NOMBRE_CATEGORIA"].ToString();
                    producto.RutaImagen = respuestaReader["RUTA_IMAGEN"].ToString();

                    productos.Add(producto);

                }
                connection.Close();
                ViewBag.Productos = productos;
            }

            sqlQuery = $"exec [OMAZON].[sp_SELECT_CATEGORIA]";
            using (SqlCommand command = new SqlCommand(sqlQuery, connection))
            {
                command.CommandType = CommandType.Text;
                connection.Open();
                SqlDataReader respuestaReader = command.ExecuteReader();

                List<CategoriaModel> categorias = new List<CategoriaModel>();
                while (respuestaReader.Read())
                {
                    CategoriaModel categoria = new CategoriaModel();

                    categoria.IdCategoria = Int32.Parse(respuestaReader["ID_CATEGORIA"].ToString());
                    categoria.NombreCategoria = respuestaReader["NOMBRE_CATEGORIA"].ToString();

                    categorias.Add(categoria);

                }
                connection.Close();
                ViewBag.Categorias = categorias;
            }
            return View();
        }


        [HttpGet]
        public IActionResult Ver(ProductoModel producto)
        {
            ViewBag.Producto = producto;
            return View();
        }


        [HttpGet]
        public IActionResult BusquedaProducto(ProductoModel productoBusqueda)
        {
            ISearchResponse<ElasticProduct> response;

            var searchRequest = new SearchRequest<ProductoModel>
            {
                Query = Query<ProductoModel>.QueryString(qs => qs.Query($"*{productoBusqueda.NombreProducto}*").DefaultField(f => f.NombreProducto).DefaultOperator(Operator.And))
            };
            response = _client.Search<ElasticProduct>(searchRequest);
            ViewBag.busqueda = response.Documents;
            ViewBag.valorBusqueda = productoBusqueda.NombreProducto;
            return View();
        }//BusquedaProducto

        public string AgregarProductoACarrito(int idProducto, int precio, int cantidad)
        {
            string connectionString = Configuration["ConnectionStrings:DB_Connection"];
            var connection = new SqlConnection(connectionString);
            var subTotal = precio * cantidad;
            string sqlQuery = $"exec [OMAZON].[sp_INSERTAR_PRODUCTO_CARRITO] '{2}'," +
                $"'{idProducto}', '{cantidad}', '{subTotal}'";
            string respuesta = "Error";
            using (SqlCommand command = new SqlCommand(sqlQuery, connection))
            {
                command.CommandType = CommandType.Text;
                connection.Open();
                SqlDataReader respuestaReader = command.ExecuteReader();


                List<ProductoModel> productos = new List<ProductoModel>();
                if (respuestaReader.Read())
                {
                    respuesta = respuestaReader["RESPUESTA"].ToString();
                }
                connection.Close();
            }
            return respuesta;
        }

        public string EliminarProductoCarrito(int idProducto)
        {
            /*
            string connectionString = Configuration["ConnectionStrings:DB_Connection"];
            var connection = new SqlConnection(connectionString);
            var subTotal = precio * cantidad;
            string sqlQuery = $"exec [OMAZON].[sp_INSERTAR_PRODUCTO_CARRITO] '{2}'," +
                $"'{idProducto}', '{cantidad}', '{subTotal}'";
            string respuesta = "Error";
            using (SqlCommand command = new SqlCommand(sqlQuery, connection))
            {
                command.CommandType = CommandType.Text;
                connection.Open();
                SqlDataReader respuestaReader = command.ExecuteReader();


                List<ProductoModel> productos = new List<ProductoModel>();
                if (respuestaReader.Read())
                {
                    respuesta = respuestaReader["RESPUESTA"].ToString();
                }
                connection.Close();
            }
            */
            return "";
        }

        [HttpPost]
        public async Task<IActionResult> ConfirmPurchaseAsync(CreditCardModel creditCardModel)
        {
            string connectionString = Configuration["ConnectionStrings:DB_Connection"];
            var connection = new SqlConnection(connectionString);
            string sqlQuery = $"exec [OMAZON].[sp_REGISTRAR_COMPRA_BY_CARRITO] " +
                $"'{HttpContext.User.FindFirstValue(ClaimTypes.Sid)}'" +
                $", '{creditCardModel.Direccion}'" +
                $", '{creditCardModel.NumeroTarjeta}'" +
                $", '{creditCardModel.CodigoSeguridad}'" +
                $", '{creditCardModel.FechaVencimiento}'";

            using SqlCommand command = new SqlCommand(sqlQuery, connection);
            command.CommandType = CommandType.Text;
            connection.Open();
            await command.ExecuteNonQueryAsync();
            connection.Close();
            TempData["isShow"] = true;
            TempData["message"] = "Compra realizada con exito";
            return RedirectToAction("Carrito", "Usuario");
        }
    }
}

MainWebApp/Omazon/Omazon/Views/Producto/BusquedaProducto.cshtml
@{

}

@model Omazon.Models.ElasticProduct

    <div class="m-1 p-2 bg-dark text-light rounded">
        <h1 class="text-center">Resultados para: </h1>
        <h2 class="text-info text-center">@ViewBag.ValorBusqueda</h2>
    </div>


    <div class="row m-1">
        @if (ViewBag.busqueda!=null)
        {
            @foreach (var producto in ViewBag.busqueda)
            {
                string imagenRuta = "/Imagenes/" + @producto.RutaImagen;
                <form method="get" asp-controller="Producto" asp-action="Ver" class="col-sm-3 my-3">

                    <div class="card">
                        <img src=@imagenRuta class="card-img-top" alt="foto-producto-de-limpieza" height="250">
                        <div class="card-body">
                            <h5 class="card-title">@producto.NombreProducto</h5>
                            <h3> Precio : @producto.Precio US$</h3>
                            <div class="row d-flex">
                                <input type="number" id="cantidad" class="form-control-sm col-4 m-auto" value="1" />
                                <button type="button" id="btnCarrito" onclick="agregarACarrito(); return false;" class="btn btn-info text-white col-7 m-auto">Agregar al carrito</button>
                            </div>
                        </div>
                        <div class="card-footer row d-flex justify-content-end m-0">
                            <input type="hidden" asp-for="@Model.IdProducto" id="idProducto"  value="@producto.IdProducto" />
                            <input type="hidden" asp-for="@Model.NombreProducto"  value="@producto.NombreProducto" />
                            <input type="hidden" asp-for="@Model.Stock"  value="@producto.Stock" />
                            <input type="hidden" asp-for="@Model.Precio" id="precio" value="@producto.Precio" />
                            <input type="hidden" asp-for="@Model.NombreProveedor" value="@producto.NombreProveedor" />
                            <input type="hidden" asp-for="@Model.NombreCategoria" value="@producto.NombreCategoria" />
                            <input type="hidden" asp-for="@Model.RutaImagen"  value="@producto.RutaImagen" />
                            <button type="submit" class="btn btn-primary col-4">Ver</button>
                        </div>
                    </div>

                </form>
            }
        }
    </div>

MainWebApp/Omazon/Omazon/Views/Producto/Index.cshtml
@model ProductoModel
@{
    ViewData["Title"] = "Gestor de productos";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="mt-4 mb-2">
    <h1 class="promo-table__title d-inline me-3">Gestor de productos</h1>
    <button class="btn mb-3 d-inline btn__add"
            data-bs-toggle="modal"
            data-bs-target="#addModal"
            data-bs-placement="right"
            title="Agregar producto"
            onclick="">
        <img src="~/Imagenes/add_black_24dp.svg" alt="Icono de agregar" />
    </button>
    <button class="btn mb-3 d-inline btn__search"
            data-bs-toggle="modal"
            data-bs-target="#searchModal"
            data-bs-placement="right"
            title="Busqueda de productos"
            onclick="">
        <img src="~/Imagenes/search_black_24dp.svg" alt="Icono de busqueda" />
    </button>
    <button class="btn mb-3 d-inline btn__refresh"
            title="Refrescar tabla" onclick="">
        <img src="~/Imagenes/refresh_black_24dp.svg" alt="Icono de busqueda" />
    </button>
</div>
<hr />
<div>
    <div class="row table-responsive">
        <div class="col-12">
            <table class="table table-bordered table-striped table-hover">
                <thead class="table-dark">
                    <tr>
                        <th scope="col">ID</th>
                        <th scope="col">Nombre</th>
                        <th scope="col">Cantidad</th>
                        <th scope="col">Precio US$</th>
                        <th scope="col">Categoria</th>
                        <th scope="col">Acción</th>
                    </tr>
                </thead>
                <tbody id="tbodyUser">
                    @if (ViewBag.Productos != null)
                    {
                        List<ProductoModel> productos = ViewBag.Productos;
                        @foreach (ProductoModel producto in productos)
                        {
                            <tr class="text-center">
                                <td>@producto.IdProducto</td>
                                <td>@producto.NombreProducto</td>
                                <td>@producto.Stock</td>
                                <td>@producto.Precio</td>
                                <td>@producto.NombreCategoria</td>
                                <td>
                                    <button class="btn btn-primary btn-sm my-1 my-xl-0" data-bs-toggle="modal" data-bs-target="#editModal" onclick="putProductOnEditModal(this); return false;">
                                        Modificar
                                        <img src="~/Imagenes/edit_white_18dp.svg" alt="Icono modificar" class="ms-2 my-1" />
                                    </button>
                                    <button class="btn btn-danger btn-sm my-1 my-xl-0" data-bs-toggle="modal" data-bs-target="#deleteModal" onclick="putProductOnDeleteModal(this); return false;">
                                        Eliminar
                                        <img src="~/Imagenes/delete_white_18dp.svg" alt="Icono eliminar" class="ms-2 my-1" />
                                    </button>
                                </td>
                            </tr>
                        }
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>
<div class="modal fade" id="searchModal" tabindex="-1" aria-labelledby="searchModal" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Busqueda de productos</h5>
            </div>
            <form class="was-validated" method="post" asp-controller="Producto" asp-action="Index">
                <div class="modal-body">
                    <div class="container">
                        <div class="mb-3">
                            <label for="" class="form-label">Nombre de producto</label>
                            <input id="" class="form-control is-invalid" type="text" placeholder="Ingrese el nombre del producto" asp-for="NombreProducto" required>
                            <span class="field-validation-error" asp-validation-for="NombreProducto"></span>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancelar</button>
                    <button id="btn-search" type="submit" class="btn btn-primary">Buscar</button>
                </div>
            </form>
        </div>
    </div>
</div>
<div class="modal fade" id="editModal" tabindex="-1" aria-labelledby="editModal" aria-hidden="true">
    <div class="modal-dialog modal-xl">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Modificar información del producto</h5>
            </div>
            <form id="formEditProductModal" class="row g-3 p-3 was-validated" method="post" asp-controller="Admin" asp-action="EditProduct">
                <input id="inputIdProduct" class="form-control is-invalid" type="hidden" asp-for="IdProducto" />
                <div class="col-md-12">
                    <label for="inputName" class="form-label">Nombre</label>
                    <input id="inputName" class="form-control is-invalid" type="text" asp-for="NombreProducto" required>
                    <span class="field-validation-error" asp-validation-for="NombreProducto"></span>
                </div>
                <div class="col-md-12">
                    <label for="inputStock" class="form-label">Cantidad</label>
                    <input id="inputStock" class="form-control is-invalid" type="text" asp-for="Stock" required>
                    <span class="field-validation-error" asp-validation-for="Stock"></span>
                </div>
                <div class="col-md-12">
                    <label for="inputPrice" class="form-label">Precio</label>
                    <input id="inputPrice" class="form-control is-invalid" type="number" asp-for="Precio" required>
                    <span class="field-validation-error" asp-validation-for="Precio"></span>
                </div>
                <div class="col-md-12">
                    <label for="inputCateg" class="form-label">Categoria</label>
                    <select id="SelectCategoria" asp-for="IDCategoria">
                        @foreach (CategoriaModel temp in ViewBag.Categorias)
                        {
                            <option value="@temp.IdCategoria">
                                @temp.NombreCategoria
                            </option>
                        }
                    </select>
                    <span class="field-validation-error" asp-validation-for="IDCategoria"></span>
                </div>
                <div class="col-md-12">
                    <label for="inputImage" class="form-label">Imagen</label>

                    <img id="laImagen" width="100" src="/Imagenes/Cargador.png" />

                    <select id="SelectRutaImagen" asp-for="RutaImagen">
                        <option value="Cargador.png">Cargador</option>
                        <option value="audifonos.png">Audifonos</option>
                        <option value="computadora.png">Computadora</option>
                        <option value="Monitor.png">Monitor</option>
                        <option value="Mouse.png">Mouse</option>
                        <option value="Teclado.png">Teclado</option>
                        <option value="USB.png">USB</option>
                        <option value="telefono.png">Telefono</option>
                        <option value="parlante.png">Parlante</option>
                    </select>
                    <span class="field-validation-error" asp-validation-for="RutaImagen"></span>
                </div>

                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancelar</button>
                    <button id="btnEdit" type="submit" class="btn btn-primary" data-bs-dismiss="modal">Actualizar</button>
                </div>
            </form>
        </div>
    </div>
</div>
<div class="modal fade" id="addModal" tabindex="-1" aria-labelledby="addModal" aria-hidden="true">
    <div class="modal-dialog modal-xl">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Registrar un nuevo producto</h5>
            </div>
            <form id="formAddProductModal" class="row g-3 p-3 was-validated" method="post" asp-controller="Admin" asp-action="CreateProduct">
                <input id="inputIdProducto" class="form-control is-invalid" type="hidden" asp-for="IdProducto" />
                <div class="col-md-12">
                    <label for="inputName" class="form-label">Nombre</label>
                    <input id="inputName" class="form-control is-invalid" type="text" placeholder="Ingrese el nombre" asp-for="NombreProducto" required>
                    <span class="field-validation-error" asp-validation-for="NombreProducto"></span>
                </div>
                <div class="col-md-12">
                    <label for="inputStock" class="form-label">Cantidad</label>
                    <input id="inputStock" class="form-control is-invalid" type="number" placeholder="Ingrese la cantidad" asp-for="Stock" required>
                    <span class="field-validation-error" asp-validation-for="Stock"></span>
                </div>
                <div class="col-md-12">
                    <label for="inputPrice" class="form-label">Precio</label>
                    <input id="inputPrice" class="form-control is-invalid" type="number" placeholder="Ingrese el precio" asp-for="Precio" required>
                    <span class="field-validation-error" asp-validation-for="Precio"></span>
                </div>
                <div class="col-md-12">
                    <label for="inputCateg" class="form-label">Categoria</label>
                    <select id="SelectCategoria" asp-for="IDCategoria">
                        @foreach (CategoriaModel temp in ViewBag.Categorias)
                        {
                            <option value="@temp.IdCategoria">
                                @temp.NombreCategoria
                            </option>
                        }
                    </select>
                    <span class="field-validation-error" asp-validation-for="IDCategoria"></span>
                </div>
                <div class="col-md-12">
                    <label for="inputImage" class="form-label">Imagen</label>

                    <img id="laImagen" width="100" src="/Imagenes/Cargador.png" />

                    <select id="SelectRutaImagen" asp-for="RutaImagen">
                        <option value="Cargador.png">Cargador</option>
                        <option value="audifonos.png">Audifonos</option>
                        <option value="computadora.png">Computadora</option>
                        <option value="Monitor.png">Monitor</option>
                        <option value="Mouse.png">Mouse</option>
                        <option value="Teclado.png">Teclado</option>
                        <option value="USB.png">USB</option>
                        <option value="telefono.png">Telefono</option>
                        <option value="parlante.png">Parlante</option>
                    </select>
                    <span class="field-validation-error" asp-validation-for="RutaImagen"></span>
                </div>

                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancelar</button>
                    <button id="btnEdit" type="submit" class="btn btn-primary" data-bs-dismiss="modal">Registrar</button>
                </div>
            </form>
        </div>
    </div>
</div>
<div class="modal fade" id="deleteModal" tabindex="-1" aria-labelledby="deleteModal" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">¿Está seguro de eliminar este producto?</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <form id="formDeleteProductModal" method="post" asp-controller="Admin" asp-action="DeleteProduct">
                <input id="inputIdProduct1" class="form-control is-invalid" type="hidden" asp-for="IdProducto" />
                <div class="col-md-12">
                    <label for="inputName1" class="form-label">Nombre</label>
                    <input id="inputName1" class="form-control is-invalid" type="text" asp-for="NombreProducto" required>
                    <span class="field-validation-error" asp-validation-for="NombreProducto"></span>
                </div>
                <div id="msgContainerDeleteModal" class="modal-body">
                    <p>El producto se eliminara permanentemente del sistema</p>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancelar</button>
                    <button type="submit" class="btn btn-primary">Confirmar eliminación</button>
                </div>
            </form>
        </div>
    </div>
</div>



@section scripts
{
    <script src="~/js/product.js" asp-append-version="true"></script>
    <partial name="_ValidationScriptsPartial" />

    <script>
        SelectRutaImagen.addEventListener("change", () => {
            laImagen.setAttribute("src", "/Imagenes/" + SelectRutaImagen.selectedOptions[0].value)
        })
    </script>
}