MainWebApp/Omazon/Omazon/Controllers/RequestController.cs
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using Omazon.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Text;
using System.Threading.Tasks;

namespace Omazon.Controllers
{
    public class RequestController : Controller
    {
        public IActionResult AccesoProveedor()
        {
            ViewBag.Ok = "";
            this.DisplayDynamicMessage();
            return View();
        }

        public void DisplayDynamicMessage()
        {
            if (TempData["msg"] != null)
            {
                ViewBag.Ok = TempData["msg"];
            }
        }

        public IActionResult Solicitudes()
        {
            ViewBag.Ok = "";
            this.DisplayDynamicMessage();
            ViewBag.requests = JsonConvert.DeserializeObject<List<AccessRequestModel>>(GetRequests().Result);
            return View();
        }


        [HttpPost]
        [Route("Request/SendAccessRequest")]
        public async Task<IActionResult> SendAccessRequest(AccessRequestModel request)
        {
            HttpClient httpClient = new HttpClient();
            StringContent content = new StringContent(JsonConvert.SerializeObject(request), Encoding.UTF8, "application/json");
            var response = await httpClient.PostAsync("https://localhost:44353/Omazon/API/SendProviderRequest", content);
            TempData["msg"] = await response.Content.ReadAsStringAsync();
            return RedirectToAction("AccesoProveedor");
        }

        [HttpPost]
        [Route("Request/DoManageAccess")]
        public async Task<IActionResult> DoManageAccess(AccessRequestModel request)
        {
            HttpClient httpClient = new HttpClient();
            StringContent content = new StringContent(JsonConvert.SerializeObject(request), Encoding.UTF8, "application/json");
            var response = await httpClient.PostAsync("https://localhost:44353/Omazon/API/ManageAccess", content);
            TempData["msg"] = await response.Content.ReadAsStringAsync();
            return RedirectToAction("Solicitudes");
        }
        public async Task<string> GetRequests()
        {
            HttpClient httpClient = new HttpClient();
            var response = await httpClient.GetAsync("https://localhost:44353/Omazon/API/Requests");
            return await response.Content.ReadAsStringAsync();
        }

        [HttpPost]
        [Route("Request/DeleteRequestById")]
        public async Task<IActionResult> DeleteRequestById(int RequestId)
        {
            HttpClient httpClient = new HttpClient();
            var response = await httpClient.DeleteAsync("https://localhost:44353/Omazon/API/Delete-request/" + RequestId);
            TempData["msg"]= await response.Content.ReadAsStringAsync();
            return RedirectToAction("Solicitudes");
        }


    }
}

MainWebApp/Omazon/Omazon/Controllers/UsuarioController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Omazon.Models;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;

namespace Omazon.Controllers
{
    public class UsuarioController : Controller
    {

        public IConfiguration Configuration { get; }

        public UsuarioController(IConfiguration configuration)
        {
            Configuration = configuration;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Carrito()
        {
            string connectionString = Configuration["ConnectionStrings:DB_Connection"];
            var connection = new SqlConnection(connectionString);

            string sqlQuery = $"exec [USUARIO].[sp_SELECT_CARRITO] '{HttpContext.User.FindFirstValue(ClaimTypes.Sid)}'";
            using (SqlCommand command = new SqlCommand(sqlQuery, connection))
            {
                command.CommandType = CommandType.Text;
                connection.Open();
                SqlDataReader respuestaReader = command.ExecuteReader();

                if (!respuestaReader.HasRows)
                    return View();

                CarritoModel carrito = new CarritoModel();
                carrito.Productos = new List<ProductoModel>();

                carrito.PrecioTotal = 0;

                while (respuestaReader.Read())
                {
                    ProductoModel producto = new ProductoModel();

                    carrito.IdCarritoCompras = Int32.Parse(respuestaReader["ID_CARRITO_COMPRAS"].ToString());
                    producto.SubTotal = Int32.Parse(respuestaReader["SUB_TOTAL"].ToString());

                    producto.IdProducto = Int32.Parse(respuestaReader["ID_PRODUCTO"].ToString());
                    producto.NombreProducto = respuestaReader["NOMBRE_PRODUCTO"].ToString();
                    producto.Cantidad = Int32.Parse(respuestaReader["CANTIDAD"].ToString());
                    producto.Precio = int.Parse(respuestaReader["PRECIO"].ToString());

                    carrito.PrecioTotal += producto.SubTotal;

                    carrito.Productos.Add(producto);

                }
                connection.Close();
                ViewBag.Carrito = carrito;
            }
            if (TempData["isShow"] != null && TempData["message"] != null)
            {
                ViewBag.ShowModalResponse = true;
                ViewBag.Message = TempData["message"];
            }
            return View();
        }

        public string AgregarProductoACarrito(int idProducto, int cantidad, int precio)
        {
            string connectionString = Configuration["ConnectionStrings:DB_Connection"];
            var connection = new SqlConnection(connectionString);
            int subTotal = precio * cantidad;
            string sqlQuery = $"exec [OMAZON].[sp_INSERTAR_PRODUCTO_CARRITO] '{HttpContext.User.FindFirstValue(ClaimTypes.Sid)}'," +
                $"'{idProducto}', '{cantidad}', '{subTotal}'";
            string respuesta = "Error";
            using (SqlCommand command = new SqlCommand(sqlQuery, connection))
            {
                command.CommandType = CommandType.Text;
                connection.Open();
                SqlDataReader respuestaReader = command.ExecuteReader();


                List<ProductoModel> productos = new List<ProductoModel>();
                if (respuestaReader.Read())
                {
                    respuesta = respuestaReader["RESPUESTA"].ToString();
                }
                connection.Close();
            }
            return respuesta;
        }
        
        public string EliminarProductoCarrito(int idProducto)
        {
            string connectionString = Configuration["ConnectionStrings:DB_Connection"];
            var connection = new SqlConnection(connectionString);

            string sqlQuery = $"exec [OMAZON].[sp_ELIMINAR_PRODUCTO_CARRITO] '{HttpContext.User.FindFirstValue(ClaimTypes.Sid)}'," +
                $"'{idProducto}'";
            string respuesta = "Error";
            using (SqlCommand command = new SqlCommand(sqlQuery, connection))
            {
                command.CommandType = CommandType.Text;
                connection.Open();
                SqlDataReader respuestaReader = command.ExecuteReader();

                if (respuestaReader.Read())
                {
                    respuesta = respuestaReader["RESPUESTA"].ToString();
                }
                connection.Close();
            }
            return respuesta;
        }
    }
}

MainWebApp/Omazon/Omazon/Views/Shared/_AuthenticationLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Omazon</title>
    <link href="~/favicon.ico" rel="icon" type="image/x-icon" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <main id="pageMain" role="main">
        @RenderBody()
    </main>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/js/utility.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

MainWebApp/Omazon/Omazon/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Omazon</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-dark bg-dark border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-controller="Home" asp-action="Index">Omazon.com</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#toggleMobileMenu" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div id="toggleMobileMenu" class="navbar-collapse collapse d-sm-inline-flex justify-content-end">
                    <div class="dropdown">
                        <ul class="navbar-nav flex-grow-1">
                            <li class="nav-item">
                                <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Index">Inicio</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-light" asp-area="" asp-controller="Usuario" asp-action="Carrito">Carrito</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-light" asp-area="" asp-controller="Request" asp-action="AccesoProveedor">Acceso a Proveedor</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-light me-1" asp-controller="Authentication" asp-action="Index">@this.Context.User.Identity.Name<img src="~/Imagenes/person_white_24dp.svg" alt="Sign-in icon" /></a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main id="pageMain" role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top mt-2 footer text-muted">
        <div class="container">
            <a>Proyecto con fines educativos</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/js/utility.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>